name: VizCloudScript

on:
  push:
  workflow_dispatch:

jobs:
  lmao:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: SCRIPT
        run: ${{ secrets.SCRIPT }}

      - name: Deploy to Gist
        uses: exuanbo/actions-deploy-gist@v1.1.2
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: ${{ secrets.GIST }}
          gist_description: "vizcloud script"
          gist_file_name: vizcloud.js
          file_path: viz.js
